#!/bin/bash

ROOT_PATH=$(realpath $(dirname "$0"))
APP_PATH="$ROOT_PATH/app"
ENV_FILENAME="$ROOT_PATH/.env"

# echo "ROOT_PATH:$ROOT_PATH" >&2
# echo "INFRA_PATH:$INFRA_PATH" >&2
# echo "INFRA_PATH:$ENV_FILENAME" >&2

set -a
. $ENV_FILENAME
set +a

cd $APP_PATH
docker build -t $(tf output -json runtime | jq -r .repository_url):latest .
docker push $(tf output -json runtime | jq -r .repository_url):latest
tf apply --auto-approve 
